pagesFiles:
  - label: "Team index"
    name: "team"
    file: "src/team.md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/team.html" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/team/" }
      - { label: "Title", name: "title", widget: "string" }
collections:
  - name: "team"
    label: "Team members"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    preview_path: "team/{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/member.html" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Qualifications", name: "qualifications", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website", name: "url", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
